### ISSUE TITLE
Search "common parameter" get 404

### ISSUE THREAD

**Issue by Folyd** [huhu/k8s-search-extension#1]
The 404 page is: https://kubernetes.io/docs/reference/kubernetes-api/common-parameters
The correct page is: https://kubernetes.io/docs/reference/kubernetes-api/common-parameters/common-parameters/

**Comment by houseme** [comment]
https://k8s.extension.sh/ chrome 的安装地址是 C++的

**Comment by Folyd** [comment]
Thanks for the feedback. I'll fix it after the Chrome Webstore approves my extension.
